from IPython import embed as shell
import itertools
import numpy as np
import random

SEED = 1234
NUM_PROBS = 5
NUM_CANS = 1 # each can i starts at target i, so we must have NUM_CANS <= NUM_TARGETS
NUM_TARGETS = 1
assert NUM_CANS <= NUM_TARGETS
# GOAL = "(RobotAt pr2 pdp_target0)"
GOAL = "(RobotAt pr2 robot_end_pose)"
# GOAL = "(At can0 target2)"
# GOAL = "(InGripper pr2 can0)"
# GOAL = "(RobotAt pr2 robot_end_pose), (InGripper pr2 can0)"

CAN_ROTATION_INIT = [0,0,0]
CAN_RADIUS = 0.04
CAN_HEIGHT = 0.25
CAN_GEOM = [CAN_RADIUS, CAN_HEIGHT]
DIST_BETWEEN_CANS = 0.01

PR2_INIT_POSE = [-1,0,0]
PR2_END_POSE = [-0,1,0]
BACKHEIGHT_INIT = [0.3]
# referred to as side2 pose in rapprentice
R_ARM_INIT = [-1.832, -0.332, -1.011, -1.437, -1.1, 0, -3.074]
# left arm is tucked
L_ARM_INIT = [0.06, 1.25, 1.79, -1.68, -1.73, -0.10, -0.09]
GRIPPER_INIT = [0.5]

ROBOT_DIST_FROM_TABLE = 0.05
# rll table
# TABLE_DIM = [2.235, 0.94]
# TABLE_THICKNESS = [0.2]
# TABLE_LEG_DIM = [1.3, 0.6]
# TABLE_LEG_HEIGHT = [0.6]
# TABLE_BACK = [False]

# small table
TABLE_DIM = [0.65, 1.5]
TABLE_THICKNESS = 0.2
TABLE_LEG_DIM = [.15, 0.2]
TABLE_LEG_HEIGHT = 0.6
TABLE_BACK = False
# TABLE_GEOM = []
TABLE_GEOM = [.325, .75, 0.1]
# for info in [TABLE_DIM, [TABLE_THICKNESS], TABLE_LEG_DIM, [TABLE_LEG_HEIGHT], [TABLE_BACK]]:
#     TABLE_GEOM.extend(info)

class CollisionFreeTargetValueGenerator(object):
    def __init__(self):
        self.max_x = TABLE_DIM[0]/2 - CAN_RADIUS
        self.min_x = -self.max_x
        self.max_y = TABLE_DIM[1]/2 - CAN_RADIUS
        self.min_y = -self.max_y
        self._poses = []

    def __iter__(self):
        return self

    def next(self):
        collides = True
        while collides:
            collides = False
            x = random.uniform(self.min_x, self.max_x)
            y = random.uniform(self.min_y, self.max_y)
            z = TABLE_LEG_HEIGHT + TABLE_THICKNESS + CAN_HEIGHT/2
            for pose in self._poses:
                diff = np.array([x - pose[0], y-pose[1]])
                if np.linalg.norm(diff) <= CAN_RADIUS*2 + DIST_BETWEEN_CANS:
                    collides = True
        pose = [x,y,z]
        self._poses.append(pose)
        return pose

    def reset(self):
        self._poses = []

def get_pr2_init_attrs_str(name):
    s = ""
    s += "(backHeight {} {}), ".format(name, BACKHEIGHT_INIT)
    s += "(lArmPose {} {}), ".format(name, L_ARM_INIT)
    s += "(lGripper {} {}), ".format(name, GRIPPER_INIT)
    s += "(rArmPose {} {}), ".format(name, R_ARM_INIT)
    s += "(rGripper {} {}), ".format(name, GRIPPER_INIT)
    return s

def get_pr2_undefined_attrs_str(name):
    s = ""
    s += "(backHeight {} undefined)".format(name)
    s += "(lArmPose {} undefined), ".format(name)
    s += "(lGripper {} undefined), ".format(name)
    s += "(rArmPose {} undefined), ".format(name)
    s += "(rGripper {} undefined), ".format(name)
    return s

def main():
    random.seed(SEED)
    target_gen = CollisionFreeTargetValueGenerator()
    for iteration in range(NUM_PROBS):
        target_gen.reset()
        s = "# AUTOGENERATED. DO NOT EDIT.\n# Configuration file for CAN problem instance. Blank lines and lines beginning with # are filtered out.\n\n"

        s += "# The values after each attribute name are the values that get passed into the __init__ method for that attribute's class defined in the domain configuration.\n"
        s += "Objects: "
        for i in range(NUM_TARGETS):
            s += "Target (name target{}); ".format(i)
            s += "EEPose (name ee_target{}); ".format(i)
            s += "RobotPose (name pdp_target{}); ".format(i)
            if i < NUM_CANS:
                s += "Can (name can{}); ".format(i)
                # s += "RobotPose (name gp_can{}); ".format(i)
        s += "Robot (name {}); ".format("pr2")
        s += "RobotPose (name {}); ".format("robot_init_pose")
        s += "RobotPose (name {}); ".format("robot_end_pose")
        s += "Obstacle (name {}) \n\n".format("table")

        s += "Init: "
        for i in range(NUM_TARGETS):
            target_pos = target_gen.next()
            s += "(geom target{} {} {}), ".format(i, CAN_GEOM[0], CAN_GEOM[1])
            s += "(value target{} {}), ".format(i, target_pos)
            s += "(rotation target{} {}),".format(i, CAN_ROTATION_INIT)
            s += "(value pdp_target{} undefined)".format(i)
            s += get_pr2_undefined_attrs_str("pdp_target{}".format(i))
            s += "(value ee_target{} undefined), ".format(i)
            s += "(rotation ee_target{} undefined), ".format(i)

            if i < NUM_CANS:
                s += "(geom can{} {} {}), ".format(i, CAN_GEOM[0], CAN_GEOM[1])
                s += "(pose can{} {}), ".format(i, target_pos)
                s += "(rotation can{} {}),".format(i, CAN_ROTATION_INIT)
                # s += "(value gp_can{} undefined), ".format(i)
        s += "(geom {}), ".format("pr2")
        # setting intial state of robot
        s += "(pose pr2 {}), ".format(PR2_INIT_POSE)
        s += get_pr2_init_attrs_str('pr2')

        s += "(value {} {}), ".format("robot_init_pose", PR2_INIT_POSE)
        s += get_pr2_init_attrs_str('robot_init_pose')
        s += "(value {} {}), ".format("robot_end_pose", PR2_END_POSE)
        s += get_pr2_init_attrs_str('robot_end_pose')

        # table pose
        z = TABLE_THICKNESS/2 + TABLE_LEG_HEIGHT
        s += "(pose {} [0, 0, {}]), ".format("table", z)
        s += "(rotation {} {}), ".format("table", CAN_ROTATION_INIT)
        s += "(geom {} {}); ".format("table", TABLE_GEOM)

        for i in range(NUM_CANS):
            s += "(At can{} target{}), ".format(i, i)
            s += "(Stationary can{}), ".format(i)
            for j in range(NUM_CANS):
                s += "(StationaryNEq can{} can{}), ".format(i, j)
            # s += "(InContact pr2 gp_can{} target{}), ".format(i, i)
            # s += "(GraspValid gp_can{} target{} grasp0), ".format(i, i)
        for i in range(NUM_TARGETS):
            s += "(InContact pr2 ee_target{} target{}), ".format(i, i)
            s += "(GraspValid ee_target{} target{}), ".format(i, i)
            s += "(GraspValidRot ee_target{} target{}), ".format(i, i)
            s += "(EEReachable pr2 pdp_target{} ee_target{}), ".format(i, i)
            s += "(EEReachableRot pr2 pdp_target{} ee_target{}), ".format(i, i)
        s += "(RobotAt pr2 robot_init_pose), "
        s += "(StationaryArms pr2), "
        s += "(StationaryBase pr2), "
        s += "(IsMP pr2), "
        s += "(WithinJointLimit pr2), "
        s += "(StationaryW table) \n\n"

        s += "Goal: {}".format(GOAL)

        with open("can_probs/can_{}_{}.prob".format(SEED, iteration), "w") as f:
            f.write(s)

if __name__ == "__main__":
    main()
