from IPython import embed as shell
import itertools
import numpy as np
import random

import core.util_classes.hsr_constants as const

# SEED = 1234
NUM_PROBS = 1
NUM_OBJS = 1
NUM_SYMBOLS = NUM_OBJS
filename = "hsr_probs/hsr.prob"
GOAL = "(HsrRobotAt hsr robot_end_pose)"
for i in range(NUM_OBJS):
    GOAL += ", (HSRCanAt can{0} can{0}_end_target)".format(i)


HSR_INIT_POSE = [0, 0, 0]
HSR_INIT_ARM = [0, -np.pi/2, 0, -np.pi/2, 0]

INT_GRIPPER = [const.GRIPPER_OEPN]
CLOSE_GRIPPER = [const.GRIPPER_CLOSE]


ROBOT_DIST_FROM_TABLE = 0.05

# TABLE_GEOM = [1.4, 1.4, 0.97/2]
TABLE_GEOM = [0.3, 0.6, 0.97/2]
# TABLE_POS = [0, 0, 0.97/2-0.375]
TABLE_POS = [1.75, 0.0, 0.97/2-0.375]
TABLE_ROT = [0,0,0]


def get_hsr_str(name, ARM = HSR_INIT_ARM, G = INT_GRIPPER, Pos = HSR_INIT_POSE):
    s = ""
    s += "(geom {})".format(name)
    s += "(arm {} {}), ".format(name, LArm)
    s += "(gripper {} {}), ".format(name, G)
    s += "(pose {} {}), ".format(name, Pos)
    return s

def get_hsr_pose_str(name, ARM = HSR_INIT_ARM, G = INT_GRIPPER, Pos = HSR_INIT_POSE):
    s = ""
    s += "(arm {} {}), ".format(name, LArm)
    s += "(gripper {} {}), ".format(name, G)
    s += "(value {} {}), ".format(name, Pos)
    return s

def get_undefined_robot_pose_str(name):
    s = ""
    s += "(arm {} undefined), ".format(name)
    s += "(gripper {} undefined), ".format(name)
    s += "(value {} undefined), ".format(name)
    return s

def get_underfine_symbol(name):
    s = ""
    s += "(value {} undefined), ".format(name)
    s += "(rotation {} undefined), ".format(name)
    return s


def save_plan(filename, obstacles=[]):
    s = "# AUTOGENERATED. DO NOT EDIT.\n# Configuration file for CAN problem instance. Blank lines and lines beginning with # are filtered out.\n\n"

    s += "# The values after each attribute name are the values that get passed into the __init__ method for that attribute's class defined in the domain configuration.\n"
    s += "Objects: "

    s += "Robot (name {}); ".format("hsr")
    for i in range(NUM_OBJS):
        s += "Can (name can{0}); ".format(i)
        s += "CanTarget (name can{0}_init_target); ".format(i)
        s += "CanTarget (name can{0}_end_target); ".format(i)
        s += "RobotPose (name {}); ".format("can_grasp_begin_{0}".format(i))
        s += "RobotPose (name {}); ".format("can_grasp_end_{0}".format(i))
        s += "RobotPose (name {}); ".format("can_putdown_begin_{0}".format(i))
        s += "RobotPose (name {}); ".format("can_putdown_end_{0}".format(i)) 
        s += "RobotPose (name {}); ".format("cg_ee_{0}".format(i))
        s += "RobotPose (name {}); ".format("cp_ee{0}".format(i))
    s += "EEPose (name cg_ee); "
    s += "EEPose (name cp_ee); "
    s += "RobotPose (name {}); ".format("robot_init_pose")
    s += "RobotPose (name {}); ".format("robot_end_pose")
    s += "RobotPose (name {}); ".format("can_grasp_begin")
    s += "RobotPose (name {}); ".format("can_grasp_end")
    s += "RobotPose (name {}); ".format("can_putdown_begin")
    s += "RobotPose (name {}); ".format("can_putdown_end")
    for o in obstacles:
        s += "Obstacle (name {}); ".format(o[0])

    s += "Obstacle (name {}); \n\n".format("table")
    s += "Init: "
    s += get_hsr_str('hsr', HSR_INIT_ARM, INT_GRIPPER, HSR_INIT_POSE)
    s += get_robot_pose_str('robot_init_pose', HSR_INIT_ARM, INT_GRIPPER, HSR_INIT_POSE)
    s += get_undefined_robot_pose_str("can_grasp_begin")
    s += get_undefined_robot_pose_str("can_grasp_end")
    s += get_undefined_robot_pose_str("can_putdown_begin")
    s += get_undefined_robot_pose_str("can_putdown_end")
    s += get_underfine_symbol("cg_ee")
    s += get_underfine_symbol("cp_ee")
    for i in range(NUM_SYMBOLS):
        s += get_undefined_robot_pose_str("can_grasp_begin_{0}".format(i))
        s += get_undefined_robot_pose_str("can_grasp_end_{0}".format(i))
        s += get_undefined_robot_pose_str("can_putdown_begin_{0}".format(i))
        s += get_undefined_robot_pose_str("can_putdown_end_{0}".format(i))
        s += get_underfine_symbol("cg_ee_{0}".format(i))
        s += get_underfine_symbol("cp_ee_{0}".format(i))
    s += get_undefined_robot_pose_str('robot_end_pose')

    s += "(geom table {}), ".format(TABLE_GEOM)
    s += "(pose table {}), ".format(TABLE_POS)
    s += "(rotation table {}); ".format(TABLE_ROT)
    for o in obstacles:
        s += "(geom {} {}), ".format(o[0], o[1])
        s += "(pose {} {}), ".format(o[0], o[2])
        s += "(rotation {} [0, 0, 0]), ".format(o[0])

    s += "(HsrRobotAt hsr robot_init_pose), "

    s += "(HSRIsMP hsr), "
    s += "(HSRWithinJointLimit hsr), "
    s += "(HSRStationaryW table) \n\n"

    s += "Goal: {}".format(GOAL)

    with open(filename, "w") as f:
        f.write(s)


if __name__ == "__main__":
    save_plan(filename)
