(cl:in-package tamp_ros-msg)
(cl:export '(SOLVER_ID-VAL
          SOLVER_ID
          PROB_ID-VAL
          PROB_ID
          SERVER_ID-VAL
          SERVER_ID
          TASK-VAL
          TASK
          STATE-VAL
          STATE
          COND-VAL
          COND
          TRAJ_MEAN-VAL
          TRAJ_MEAN
          USE_PRIOR-VAL
          USE_PRIOR
          SIGMA-VAL
          SIGMA
          MU-VAL
          MU
          LOGMASS-VAL
          LOGMASS
          MASS-VAL
          MASS
          N-VAL
          N
          K-VAL
          K
          DO-VAL
          DO
))