// Generated by gencpp from file tamp_ros/PlanProb.msg
// DO NOT EDIT!


#ifndef TAMP_ROS_MESSAGE_PLANPROB_H
#define TAMP_ROS_MESSAGE_PLANPROB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tamp_ros
{
template <class ContainerAllocator>
struct PlanProb_
{
  typedef PlanProb_<ContainerAllocator> Type;

  PlanProb_()
    : prob_id(0)
    , task()
    , object()
    , target()
    , state()  {
    }
  PlanProb_(const ContainerAllocator& _alloc)
    : prob_id(0)
    , task(_alloc)
    , object(_alloc)
    , target(_alloc)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _prob_id_type;
  _prob_id_type prob_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _task_type;
  _task_type task;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_type;
  _object_type object;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _target_type;
  _target_type target;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::tamp_ros::PlanProb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tamp_ros::PlanProb_<ContainerAllocator> const> ConstPtr;

}; // struct PlanProb_

typedef ::tamp_ros::PlanProb_<std::allocator<void> > PlanProb;

typedef boost::shared_ptr< ::tamp_ros::PlanProb > PlanProbPtr;
typedef boost::shared_ptr< ::tamp_ros::PlanProb const> PlanProbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tamp_ros::PlanProb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tamp_ros::PlanProb_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tamp_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tamp_ros': ['/home/michaelmcdonald/dependencies/tampy/src/ros_utils/src/tamp_ros/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tamp_ros::PlanProb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tamp_ros::PlanProb_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tamp_ros::PlanProb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tamp_ros::PlanProb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tamp_ros::PlanProb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tamp_ros::PlanProb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tamp_ros::PlanProb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bacbc44c2a384d436608cc453c774b3b";
  }

  static const char* value(const ::tamp_ros::PlanProb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbacbc44c2a384d43ULL;
  static const uint64_t static_value2 = 0x6608cc453c774b3bULL;
};

template<class ContainerAllocator>
struct DataType< ::tamp_ros::PlanProb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tamp_ros/PlanProb";
  }

  static const char* value(const ::tamp_ros::PlanProb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tamp_ros::PlanProb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 prob_id\n\
string task\n\
string object\n\
string target\n\
float32[] state\n\
";
  }

  static const char* value(const ::tamp_ros::PlanProb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tamp_ros::PlanProb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.prob_id);
      stream.next(m.task);
      stream.next(m.object);
      stream.next(m.target);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanProb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tamp_ros::PlanProb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tamp_ros::PlanProb_<ContainerAllocator>& v)
  {
    s << indent << "prob_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.prob_id);
    s << indent << "task: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.task);
    s << indent << "object: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object);
    s << indent << "target: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.target);
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAMP_ROS_MESSAGE_PLANPROB_H
