python policy_hooks/vae/run_training.py -env_path baxter_gym.envs.baxter_block_stack_env -env BaxterLeftBlockStackEnv -nts 1000 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py -env_path baxter_gym.envs.baxter_block_stack_env -env BaxterLeftBlockStackEnv -nts 2000 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py -env_path baxter_gym.envs.baxter_block_stack_env -env BaxterLeftBlockStackEnv -nts 3000 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py -env_path baxter_gym.envs.baxter_block_stack_env -env BaxterLeftBlockStackEnv -nts 4000 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py -env_path baxter_gym.envs.baxter_block_stack_env -env BaxterLeftBlockStackEnv -nts 5000 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py -env_path baxter_gym.envs.baxter_block_stack_env -env BaxterLeftBlockStackEnv -nts 6000 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py -env_path baxter_gym.envs.baxter_block_stack_env -env BaxterLeftBlockStackEnv -nts 7000 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py -env_path baxter_gym.envs.baxter_block_stack_env -env BaxterLeftBlockStackEnv -nts 8000 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py -env_path baxter_gym.envs.baxter_block_stack_env -env BaxterLeftBlockStackEnv -nts 9000 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py -env_path baxter_gym.envs.baxter_block_stack_env -env BaxterLeftBlockStackEnv -nts 10000 -ncp -rl 20 -tv -rnn -over -beta 5 &
