python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 5 -ncp -vae -id 0 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 5 -ncp -sim -id 0 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 5 -ncp -sim -id 1 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 5 -ncp -sim -id 2 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 5 -ncp -sim -id 3 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 5 -ncp -sim -id 4 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 5 -ncp -sim -id 5 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 5 -ncp -sim -id 6 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 5 -ncp -sim -id 7 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 5 -ncp -sim -id 8 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 5 -ncp -sim -id 9 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 5 -ncp -sim -id 10 &
