python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 4  -nts 100 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 4  -nts 200 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 4  -nts 300 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 4  -nts 400 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 4  -nts 500 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 4  -nts 600 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 4  -nts 700 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 4  -nts 800 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 4  -nts 900 -ncp -rl 20 -tv -rnn -over -beta 5 &
python policy_hooks/vae/run_training.py --config namo.namo_hyperparams -n 1 -o 4  -nts 1000 -ncp -rl 20 -tv -rnn -over -beta 5 &
