from IPython import embed as shell
import itertools
import numpy as np
import random

# SEED = 1234
NUM_PROBS = 1
NUM_CLOTHS = 1
NUM_SYMBOLS = NUM_CLOTHS
filename = "laundry_probs/folding.prob"
GOAL = "(BaxterRobotAt baxter robot_end_pose)"
for i in range(NUM_CLOTHS):
    GOAL += ", (BaxterClothAt cloth{0} cloth{0}_end_target)".format(i)


CLOTH_CAPSULES = (6, 3)

# init Baxter pose
BAXTER_INIT_POSE = [0]
R_ARM_INIT = [-np.pi/4, -np.pi/4, 0, 0, 0, 0, 0]
L_ARM_INIT = [np.pi/4, -np.pi/4, 0, 0, 0, 0, 0]
INT_GRIPPER = [0.02]
CLOSE_GRIPPER = [0.015]


ROBOT_DIST_FROM_TABLE = 0.05

# TABLE_GEOM = [1.4, 1.4, 0.97/2]
TABLE_GEOM = [0.3, 0.6, 0.97/2]
# TABLE_POS = [0, 0, 0.97/2-0.375]
TABLE_POS = [0.75, 0.0, 0.97/2-0.375]
TABLE_ROT = [0,0,0]


def get_baxter_str(name, LArm = L_ARM_INIT, RArm = R_ARM_INIT, G = INT_GRIPPER, Pos = BAXTER_INIT_POSE):
    s = ""
    s += "(geom {})".format(name)
    s += "(lArmPose {} {}), ".format(name, LArm)
    s += "(lGripper {} {}), ".format(name, G)
    s += "(rArmPose {} {}), ".format(name, RArm)
    s += "(rGripper {} {}), ".format(name, G)
    s += "(pose {} {}), ".format(name, Pos)
    return s

def get_robot_pose_str(name, LArm = L_ARM_INIT, RArm = R_ARM_INIT, G = INT_GRIPPER, Pos = BAXTER_INIT_POSE):
    s = ""
    s += "(lArmPose {} {}), ".format(name, LArm)
    s += "(lGripper {} {}), ".format(name, G)
    s += "(rArmPose {} {}), ".format(name, RArm)
    s += "(rGripper {} {}), ".format(name, G)
    s += "(value {} {}), ".format(name, Pos)
    return s

def get_undefined_robot_pose_str(name):
    s = ""
    s += "(lArmPose {} undefined), ".format(name)
    s += "(lGripper {} undefined), ".format(name)
    s += "(rArmPose {} undefined), ".format(name)
    s += "(rGripper {} undefined), ".format(name)
    s += "(value {} undefined), ".format(name)
    return s

def get_underfine_symbol(name):
    s = ""
    s += "(value {} undefined), ".format(name)
    s += "(rotation {} undefined), ".format(name)
    return s


def main():
    for iteration in range(NUM_PROBS):
        s = "# AUTOGENERATED. DO NOT EDIT.\n# Configuration file for CAN problem instance. Blank lines and lines beginning with # are filtered out.\n\n"

        s += "# The values after each attribute name are the values that get passed into the __init__ method for that attribute's class defined in the domain configuration.\n"
        s += "Objects: "

        s += "Robot (name {}); ".format("baxter")
        for i in range(NUM_SYMBOLS):
            s += "EEPose (name {}); ".format("cg_ee_left_{0}".format(i))
            s += "EEPose (name {}); ".format("cp_ee_left_{0}".format(i))
            s += "EEPose (name {}); ".format("cg_ee_right_{0}".format(i))
            s += "EEPose (name {}); ".format("cp_ee_right_{0}".format(i))
            s += "RobotPose (name {}); ".format("cloth_grasp_begin_{0}".format(i))
            s += "RobotPose (name {}); ".format("cloth_grasp_end_{0}".format(i))
            s += "RobotPose (name {}); ".format("cloth_putdown_begin_{0}".format(i))
            s += "RobotPose (name {}); ".format("cloth_putdown_end_{0}".format(i))
        
        s += "RobotPose (name {}); ".format("robot_init_pose")
        s += "RobotPose (name {}); ".format("robot_end_pose")

        for i in range(NUM_CLOTHS):
            s += "Cloth (name {}); ".format("cloth{0}".format(i))
            s += "ClothTarget (name {}); ".format("cloth{0}_init_target".format(i))
            s += "ClothTarget (name {});".format("cloth{0}_end_target".format(i))
            s += "Can (name {});".format("edge{0}".format(i))
            s += "ClothTarget (name {}); ".format("edge{0}_init_target".format(i))
            s += "ClothTarget (name {});".format("edge{0}_end_target".format(i))

        for i in range(CLOTH_CAPSULES[0]):
            for j in range(CLOTH_CAPSULES[1]):
                s += "Cloth (name {}); ".format("B{0}_{1}".format(i, j))


        s += "Obstacle (name {}); \n\n".format("table")

        s += "Init: "
        for i in range(NUM_CLOTHS):
            s += "(geom cloth{0}), ".format(i)
            s += "(pose cloth{0} {1}), ".format(i, [0, 0, 0.615])
            s += "(rotation cloth{0} {1}), ".format(i, [0, 0, 0])

            s += "(value cloth{0}_init_target {1}), ".format(i, [0, 0, 0.615])
            s += "(rotation cloth{0}_init_target {1}), ".format(i, [0, 0, 0])

            s += "(value cloth{0}_end_target {1}), ".format(i, [0, 0, 0.615])
            s += "(rotation cloth{0}_end_target {1}), ".format(i, [0, 0, 0])

            s += "(geom edge{0} {1} {2}), ".format(i, 0.01, 0.5)
            s += "(pose edge{0} {1}), ".format(i, [0, 0, 0])
            s += "(rotation edge{0} {1}), ".format(i, [0, 0, 0])

            s += "(value edge{0}_init_target {1}), ".format(i, [0, 0, 0])
            s += "(rotation edge{0}_init_target {1}), ".format(i, [0, 0, 0])

            s += "(value edge{0}_end_target {1}), ".format(i, [0, 0, 0])
            s += "(rotation edge{0}_end_target {1}), ".format(i, [0, 0, 0])

        for i in range(CLOTH_CAPSULES[0]):
            for j in range(CLOTH_CAPSULES[1]):
                s += "(geom B{0}_{1}), ".format(i, j)
                s += "(pose B{0}_{1} {2}), ".format(i, j, [0, 0, 0])
                s += "(rotation B{0}_{1} {2}), ".format(i, j, [0, 0, 0])

        s += get_baxter_str('baxter', L_ARM_INIT, R_ARM_INIT, INT_GRIPPER, BAXTER_INIT_POSE)
        s += get_robot_pose_str('robot_init_pose', L_ARM_INIT, R_ARM_INIT, INT_GRIPPER, BAXTER_INIT_POSE)
        for i in range(NUM_SYMBOLS):
            s += get_undefined_robot_pose_str("cloth_grasp_begin_{0}".format(i))
            s += get_undefined_robot_pose_str("cloth_grasp_end_{0}".format(i))
            s += get_undefined_robot_pose_str("cloth_putdown_begin_{0}".format(i))
            s += get_undefined_robot_pose_str("cloth_putdown_end_{0}".format(i))
            s += get_underfine_symbol("cg_ee_left_{0}".format(i))
            s += get_underfine_symbol("cp_ee_left_{0}".format(i))
            s += get_underfine_symbol("cg_ee_right_{0}".format(i))
            s += get_underfine_symbol("cp_ee_right_{0}".format(i))
        s += get_robot_pose_str('robot_end_pose', L_ARM_INIT, R_ARM_INIT, INT_GRIPPER, BAXTER_INIT_POSE)

        s += "(geom table {}), ".format(TABLE_GEOM)
        s += "(pose table {}), ".format(TABLE_POS)
        s += "(rotation table {}); ".format(TABLE_ROT)

        s += "(BaxterRobotAt baxter robot_init_pose), "
        # for i in range(NUM_CLOTHS):
        #     s += "(BaxterClothTargetHor cloth{0}_end_target), ".format(i)

        # for i in range(NUM_CLOTHS):
        #     s += "(BaxterClothTargetVer cloth{0}_end_target), ".format(i)

        s += "(BaxterStationaryBase baxter), "
        s += "(BaxterIsMP baxter), "
        s += "(BaxterWithinJointLimit baxter), "
        s += "(BaxterStationaryW table) \n\n"

        s += "Goal: {}".format(GOAL)

        with open(filename, "w") as f:
            f.write(s)

if __name__ == "__main__":
    main()
