from IPython import embed as shell
import itertools
import random

SEED = 1234
NUM_PROBS = 5
WIDTH = 8
HEIGHT = 9
SIZE = 1
NUM_CANS = 2 # each can i starts at target i, so we must have NUM_CANS <= NUM_TARGETS
NUM_TARGETS = 3
GOAL = "(At can0 target1), (At can1 target0)"

def main():
    random.seed(SEED)
    for iteration in range(NUM_PROBS):
        s = "# AUTOGENERATED. DO NOT EDIT.\n# Configuration file for NAMO problem instance. Blank lines and lines beginning with # are filtered out.\n\n"
        coords = list(itertools.product(range(HEIGHT), range(WIDTH)))
        random.shuffle(coords)
        coord_ind = 0
        s += "# The values after each attribute name are the values that get passed into the __init__ method for that attribute's class defined in the domain configuration.\n"
        s += "Objects: "
        for i in range(NUM_TARGETS):
            s += "Target (name target%d); "%(i)
            s += "RobotPose (name pdp_target%d); "%i
            if i < NUM_CANS:
                s += "Can (name can%d); "%i
                s += "RobotPose (name gp_can%d); "%i
        s += "Robot (name %s); "%"pr2"
        s += "RobotPose (name %s); "%"robot_init_pose"
        s += "Workspace (name ws)\n\n"

        s += "Init: "
        for i in range(NUM_TARGETS):
            s += "(geom target%d 1), (pose target%d %s), "%(i, i, coords[i])
            s += "(value pdp_target%d undefined), "%i
        for i in range(NUM_CANS):
            s += "(geom can%d 1), (pose can%d %s), "%(i, i, coords[i])
            s += "(value gp_can%d undefined), "%i
        s += "(geom %s 1), (pose %s %s), "%("pr2", "pr2", coords[NUM_TARGETS])
        s += "(value %s %s), "%("robot_init_pose", coords[NUM_TARGETS])
        s += "(pose ws (0, 0)), (w wd %d), (h wd %d), (size wd %d), (viewer wd TODO); "%(WIDTH, HEIGHT, SIZE)
        for i in range(NUM_CANS):
            s += "(At can%d target%d), "%(i, i)
            s += "(IsGP gp_can%d can%d), "%(i, i)
        for i in range(NUM_TARGETS):
            s += "(IsPDP pdp_target%d target%d), "%(i, i)
        s += "(RobotAt pr2 robot_init_pose)\n\n"

        s += "Goal: %s"%GOAL

        with open("namo_probs/namo_%d_%d.prob"%(SEED, iteration), "w") as f:
            f.write(s)

if __name__ == "__main__":
    main()
