from IPython import embed as shell
import itertools
import random

SEED = 1234
NUM_PROBS = 5
WIDTH = 8
HEIGHT = 9
SIZE = 1
NUM_CANS = 2 # each can i starts at target i, so we must have NUM_CANS <= NUM_TARGETS
NUM_TARGETS = 3
GOAL = "(At can0 target1), (At can1 target0)"

def main():
    random.seed(SEED)
    for iteration in range(NUM_PROBS):
        s = "# AUTOGENERATED. DO NOT EDIT.\n# Configuration file for NAMO problem instance. Blank lines and lines beginning with # are filtered out.\n\n"
        coords = list(itertools.product(range(HEIGHT), range(WIDTH)))
        random.shuffle(coords)
        coord_ind = 0
        s += "# The values after each attribute name are the values that get passed into the __init__ method for that attribute's class defined in the domain configuration.\n"
        s += "Objects: "
        for i in range(NUM_TARGETS):
            s += "Target (name target%d. geom 1. pose %s); "%(i, coords[i])
            s += "Symbol (name pdp_target%d. value undefined); "%i
            if i < NUM_CANS:
                s += "Can (name can%d. geom 1. pose %s); "%(i, coords[i])
                s += "Symbol (name gp_can%d. value undefined); "%i
        s += "Robot (name %s. geom 1. pose %s); "%("pr2", coords[NUM_TARGETS])
        s += "Symbol (name %s. value %s); "%("robot_init_pose", coords[NUM_TARGETS])
        s += "Workspace (name ws. w %d. h %d. size %d. viewer TODO)\n\n"%(WIDTH, HEIGHT, SIZE)

        s += "Init: "
        for i in range(NUM_CANS):
            s += "(At can%d target%d), "%(i, i)
            s += "(IsGP gp_can%d can%d), "%(i, i)
        for i in range(NUM_TARGETS):
            s += "(IsPDP pdp_target%d target%d), "%(i, i)
        s += "(RobotAt pr2 robot_init_pose)\n\n"

        s += "Goal: %s"%GOAL

        with open("namo_probs/namo_%d_%d.prob"%(SEED, iteration), "w") as f:
            f.write(s)

if __name__ == "__main__":
    main()
