(define (domain sorting_domain)
    (:requirements :equality)
    (:predicates (CanAtTarget ?can - Can ?target - Target)
                 (CanInGripper ?can - Can)
                 (CanObstructs ?can1 - Can ?can2 - Can)
                 (CanObstructsTarget ?can - Can ?target - Target)
                 (CanInReach ?can - Can)
    )

    (:types Can Target)

    (:action grasp
        :parameters (?can - Can)
        :precondition (forall (?c - Can) (not (CanObstructs ?c ?can)))
        :effect (and (CanInGripper ?can)
                     (forall (?c - Can) (when (not (= ?c ?can)) (not (CanInGripper ?c)))))
    )

    (:action putdown
        :parameters (?can - Can ?target - Target)
        :precondition (and (CanInGripper ?can)
                           (forall (?c - Can) (not (CanAtTarget ?c ?target)))
                           (forall (?c - Can) (not (CanObstructsTarget ?c ?target))))
        :effect (and (not (CanInGripper ?can))
                     (CanAtTarget ?can ?target)
                     (forall (?c - Can) (not (CanObstructs ?can ?c)))
                     (forall (?t - Target) (when (not (= ?t ?target)) (not (CanAtTarget ?can ?t))))
                     (forall (?t - Target) (when (not (= ?t ?target)) (not (CanObstructsTarget ?can ?t)))))
    )
)
