python3.6 -W ignore policy_hooks/run_training.py -c policy_hooks.robodesk.hyp \
                                               -no 1 -llus 5000  -hlus 5000 \
                                               -ff 1. -mask -hln 2 -lln 2 -hldim 64 -lldim 64 \
                                               -eta 5 \
                                               -hist_len 1 -prim_first_wt 5 -lr 0.0002 \
                                               -hllr 0.0002 -lldec 0.000001 -hldec 0.0001 \
                                               -add_noop 0 --permute_hl 0 \
                                               -image -hl_image \
                                               -imwidth 84 -imheight 84 \
                                               -expl_wt 5 -expl_eta 4 \
                                               -motion 18 \
                                               -task 2 \
                                               -rollout 10 \
                                               -warm 100 \
                                               -verbose \
                                               --load_render \
                                               -pre -post \
                                               -roll_opt \
                                               -seq \
                                               -neg_ratio 0.0 -opt_ratio 0.5 -dagger_ratio 0.5 -roll_ratio 0.000 \
                                               -descr robodesk_lift_block 

