// Generated by gencpp from file tamp_ros/HLProblem.msg
// DO NOT EDIT!


#ifndef TAMP_ROS_MESSAGE_HLPROBLEM_H
#define TAMP_ROS_MESSAGE_HLPROBLEM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tamp_ros
{
template <class ContainerAllocator>
struct HLProblem_
{
  typedef HLProblem_<ContainerAllocator> Type;

  HLProblem_()
    : solver_id(0)
    , server_id(0)
    , init_state()
    , cond(0)
    , path_to()  {
    }
  HLProblem_(const ContainerAllocator& _alloc)
    : solver_id(0)
    , server_id(0)
    , init_state(_alloc)
    , cond(0)
    , path_to(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _solver_id_type;
  _solver_id_type solver_id;

   typedef int32_t _server_id_type;
  _server_id_type server_id;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _init_state_type;
  _init_state_type init_state;

   typedef int32_t _cond_type;
  _cond_type cond;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_to_type;
  _path_to_type path_to;





  typedef boost::shared_ptr< ::tamp_ros::HLProblem_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tamp_ros::HLProblem_<ContainerAllocator> const> ConstPtr;

}; // struct HLProblem_

typedef ::tamp_ros::HLProblem_<std::allocator<void> > HLProblem;

typedef boost::shared_ptr< ::tamp_ros::HLProblem > HLProblemPtr;
typedef boost::shared_ptr< ::tamp_ros::HLProblem const> HLProblemConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tamp_ros::HLProblem_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tamp_ros::HLProblem_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tamp_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tamp_ros': ['/home/michaelmcdonald/dependencies/tampy/src/ros_utils/src/tamp_ros/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tamp_ros::HLProblem_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tamp_ros::HLProblem_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tamp_ros::HLProblem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tamp_ros::HLProblem_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tamp_ros::HLProblem_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tamp_ros::HLProblem_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tamp_ros::HLProblem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a2adc264904a8c2fffd546791b7a9ec";
  }

  static const char* value(const ::tamp_ros::HLProblem_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a2adc264904a8c2ULL;
  static const uint64_t static_value2 = 0xfffd546791b7a9ecULL;
};

template<class ContainerAllocator>
struct DataType< ::tamp_ros::HLProblem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tamp_ros/HLProblem";
  }

  static const char* value(const ::tamp_ros::HLProblem_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tamp_ros::HLProblem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 solver_id\n\
int32 server_id\n\
float32[] init_state\n\
int32 cond\n\
string path_to\n\
";
  }

  static const char* value(const ::tamp_ros::HLProblem_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tamp_ros::HLProblem_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.solver_id);
      stream.next(m.server_id);
      stream.next(m.init_state);
      stream.next(m.cond);
      stream.next(m.path_to);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HLProblem_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tamp_ros::HLProblem_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tamp_ros::HLProblem_<ContainerAllocator>& v)
  {
    s << indent << "solver_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.solver_id);
    s << indent << "server_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.server_id);
    s << indent << "init_state[]" << std::endl;
    for (size_t i = 0; i < v.init_state.size(); ++i)
    {
      s << indent << "  init_state[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.init_state[i]);
    }
    s << indent << "cond: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cond);
    s << indent << "path_to: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path_to);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAMP_ROS_MESSAGE_HLPROBLEM_H
