// Generated by gencpp from file tamp_ros/PolicyActResponse.msg
// DO NOT EDIT!


#ifndef TAMP_ROS_MESSAGE_POLICYACTRESPONSE_H
#define TAMP_ROS_MESSAGE_POLICYACTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tamp_ros
{
template <class ContainerAllocator>
struct PolicyActResponse_
{
  typedef PolicyActResponse_<ContainerAllocator> Type;

  PolicyActResponse_()
    : act()  {
    }
  PolicyActResponse_(const ContainerAllocator& _alloc)
    : act(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _act_type;
  _act_type act;





  typedef boost::shared_ptr< ::tamp_ros::PolicyActResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tamp_ros::PolicyActResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PolicyActResponse_

typedef ::tamp_ros::PolicyActResponse_<std::allocator<void> > PolicyActResponse;

typedef boost::shared_ptr< ::tamp_ros::PolicyActResponse > PolicyActResponsePtr;
typedef boost::shared_ptr< ::tamp_ros::PolicyActResponse const> PolicyActResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tamp_ros::PolicyActResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tamp_ros::PolicyActResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tamp_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tamp_ros': ['/home/michaelmcdonald/dependencies/tampy/src/ros_utils/src/tamp_ros/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tamp_ros::PolicyActResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tamp_ros::PolicyActResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tamp_ros::PolicyActResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tamp_ros::PolicyActResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tamp_ros::PolicyActResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tamp_ros::PolicyActResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tamp_ros::PolicyActResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90891bbf8bb50ef502f4296a9265197f";
  }

  static const char* value(const ::tamp_ros::PolicyActResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90891bbf8bb50ef5ULL;
  static const uint64_t static_value2 = 0x02f4296a9265197fULL;
};

template<class ContainerAllocator>
struct DataType< ::tamp_ros::PolicyActResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tamp_ros/PolicyActResponse";
  }

  static const char* value(const ::tamp_ros::PolicyActResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tamp_ros::PolicyActResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float32[] act\n\
\n\
";
  }

  static const char* value(const ::tamp_ros::PolicyActResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tamp_ros::PolicyActResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.act);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PolicyActResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tamp_ros::PolicyActResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tamp_ros::PolicyActResponse_<ContainerAllocator>& v)
  {
    s << indent << "act[]" << std::endl;
    for (size_t i = 0; i < v.act.size(); ++i)
    {
      s << indent << "  act[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.act[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAMP_ROS_MESSAGE_POLICYACTRESPONSE_H
