// Generated by gencpp from file tamp_ros/PolicyAct.msg
// DO NOT EDIT!


#ifndef TAMP_ROS_MESSAGE_POLICYACT_H
#define TAMP_ROS_MESSAGE_POLICYACT_H

#include <ros/service_traits.h>


#include <tamp_ros/PolicyActRequest.h>
#include <tamp_ros/PolicyActResponse.h>


namespace tamp_ros
{

struct PolicyAct
{

typedef PolicyActRequest Request;
typedef PolicyActResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PolicyAct
} // namespace tamp_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tamp_ros::PolicyAct > {
  static const char* value()
  {
    return "e3eb5859ffc1c0de9d569f656c4594dc";
  }

  static const char* value(const ::tamp_ros::PolicyAct&) { return value(); }
};

template<>
struct DataType< ::tamp_ros::PolicyAct > {
  static const char* value()
  {
    return "tamp_ros/PolicyAct";
  }

  static const char* value(const ::tamp_ros::PolicyAct&) { return value(); }
};


// service_traits::MD5Sum< ::tamp_ros::PolicyActRequest> should match 
// service_traits::MD5Sum< ::tamp_ros::PolicyAct > 
template<>
struct MD5Sum< ::tamp_ros::PolicyActRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tamp_ros::PolicyAct >::value();
  }
  static const char* value(const ::tamp_ros::PolicyActRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tamp_ros::PolicyActRequest> should match 
// service_traits::DataType< ::tamp_ros::PolicyAct > 
template<>
struct DataType< ::tamp_ros::PolicyActRequest>
{
  static const char* value()
  {
    return DataType< ::tamp_ros::PolicyAct >::value();
  }
  static const char* value(const ::tamp_ros::PolicyActRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tamp_ros::PolicyActResponse> should match 
// service_traits::MD5Sum< ::tamp_ros::PolicyAct > 
template<>
struct MD5Sum< ::tamp_ros::PolicyActResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tamp_ros::PolicyAct >::value();
  }
  static const char* value(const ::tamp_ros::PolicyActResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tamp_ros::PolicyActResponse> should match 
// service_traits::DataType< ::tamp_ros::PolicyAct > 
template<>
struct DataType< ::tamp_ros::PolicyActResponse>
{
  static const char* value()
  {
    return DataType< ::tamp_ros::PolicyAct >::value();
  }
  static const char* value(const ::tamp_ros::PolicyActResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAMP_ROS_MESSAGE_POLICYACT_H
